### ISSUE TITLE
missing lsf linked document

### ISSUE THREAD

**Issue by hgy59** [autarchprinceps/MultiCastor#71]
create a local clone after installing git lfs.
got one error due missing lfs content:

```
Encountered 1 file(s) that should have been pointers, but weren't:
Vorgängerversionen/V2.1/Documentation/TIT10AID_STP_Multicastor_Team_3_1v1-2.docx
```

**Comment by autarchprinceps** [comment]
Hmm, I couldn't reproduce that error. I forced a recreation to a new LFS file, so if there is some issue with the specific revision, it shouldn't occur again, but as I said, it doesn't appear for me, so I cannot test whether that fixes it.

**Comment by hgy59** [comment]
thanks, just tried another clone and the error is gone.
